### ISSUE TITLE
When nenv is missing from path (or in general), script breaks

### ISSUE THREAD

**Issue by david0673** [ekampf/dotfiles#2]
If missing nenv, script installs it but does not add to path, so breaks anyway

**Comment by david0673** [comment]
hi @ekampf :)
I will try to submit a PR later today!

**Comment by david0673** [comment]
Hi @ekampf! :)

I couldn't submit my branch :(
In order to fix in bootstrap.rb line 239, change
`run %{export PATH=$PATH:~/.nenv}  # just to make sure`
into 
`run %{export PATH=$PATH:~/.nenv/bin}  # just to make sure`

**Comment by ekampf** [comment]
Thanks!
Will check this out Monday (Im out of office)

**Comment by david0673** [comment]
Yeah, I saw!
Beautiful pictures; seemed like an awesome trip!
